version: '3.8'
services:
  #application
  vanillio_app:
    container_name: app
    build:
      context: ./dockerFiles/php/
    ports:
      - '9002:9000'
    volumes:
      - ./:/var/www/app
    networks:
      - vanillio

  #database
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
      MYSQL_DATABASE: db
    ports:
      - '4306:3306'
    networks:
      - vanillio
    volumes:
      - ./dockerFiles/mysql/dbData:/var/lib/mysql

  #webserver
  vanillio_nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8001:80'
    volumes:
      - ./:/var/www/app
      - ./dockerFiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vanillio
    depends_on:
      - vanillio_app
networks:
  vanillio: